### ISSUE TITLE
jsreport azure function issue

### ISSUE THREAD

**Issue by yauheni-p** [jsreport/jsreport-azure-functions-starter-kit#1] opened 2021-03-23 09:08 UTC
Hello. I've deployed function with some templates, which helps me to generate pdf reports. It works perfectly for a while. But after some period of time (it can be an hour or 12 hours), I start getting an empty pdf in response. Then, I wait some time(maybe an hour) , and the function starts generating a proper pdf (but not always). Any thoughts on this?

**Comment by pofider** [comment] 2021-03-23 09:35
No idea... Try to isolate the problem.
Does it happen for all templates? Even the "Hellow world one"?
Does it happen also for HTML recipes?

I see you can write some logs to `context.log` in azure functions. Perhaps you could pipe jsreport logs there.

**Comment by yauheni-p** [comment] 2021-03-23 11:38
@pofider Thank you for answer! A bit more details. I have three templates. When the first one starts producing empty pdfs, other templates still works fine. The templates are very similar to each other, but the first is the biggest(contains about 15 pages) and it used more often. I've got some logs from my function (request with empty pdf in response):
2021-03-23T11:22:20Z   [Information]   Request
2021-03-23T11:22:20Z   [Information]   Template:
2021-03-23T11:22:20Z   [Information]   {"name":"profile-main"}
2021-03-23T11:22:20Z   [Information]   TemplateName:
2021-03-23T11:22:20Z   [Information]   "profile-main"
2021-03-23T11:22:20Z   [Information]   Data:
2021-03-23T11:22:20Z   [Information]   {here is my correct json data object}
2021-03-23T11:22:20Z   [Information]   2021-03-23T11:22:20.275Z - [32minfo[39m: Starting rendering request 11 (user: null)
2021-03-23T11:22:20Z   [Information]   2021-03-23T11:22:20.282Z - [34mdebug[39m: Inline data specified.
2021-03-23T11:22:20Z   [Information]   2021-03-23T11:22:20.284Z - [34mdebug[39m: Resources not defined for this template.
2021-03-23T11:22:20Z   [Information]   2021-03-23T11:22:20.287Z - [34mdebug[39m: Base url not specified, skipping its injection.
2021-03-23T11:22:20Z   [Information]   2021-03-23T11:22:20.277Z - [32minfo[39m: Rendering template { name: profile-main, recipe: chrome-pdf, engine: handlebars, preview: false }
2021-03-23T11:22:20Z   [Information]   2021-03-23T11:22:20.292Z - [34mdebug[39m: Rendering engine handlebars using dedicated-process strategy
2021-03-23T11:22:21Z   [Information]   2021-03-23T11:22:20.608Z - [34mdebug[39m: Compiled template not found in the cache, compiling
2021-03-23T11:22:21Z   [Information]   2021-03-23T11:22:20.615Z - [34mdebug[39m: Executing recipe chrome-pdf
2021-03-23T11:22:21Z   [Information]   2021-03-23T11:22:20.832Z - [34mdebug[39m: Converting with chrome HeadlessChrome/79.0.3945.0 using dedicated-process strategy
2021-03-23T11:22:21Z   [Information]   2021-03-23T11:22:21.054Z - [34mdebug[39m: Page request: GET (document) file:///tmp/jsreport/autocleanup/30f57d3d-b681-474b-802f-4250499de245-chrome-pdf.html
2021-03-23T11:22:21Z   [Information]   2021-03-23T11:22:21.075Z - [34mdebug[39m: Page request finished: GET (document) file:///tmp/jsreport/autocleanup/30f57d3d-b681-474b-802f-4250499de245-chrome-pdf.html
2021-03-23T11:22:21Z   [Information]   2021-03-23T11:22:21.082Z - [34mdebug[39m: Running chrome with params {"printBackground":true,"margin":{}}
2021-03-23T11:22:21Z   [Information]   2021-03-23T11:22:21.142Z - [34mdebug[39m: Skipping storing report.
2021-03-23T11:22:21Z   [Information]   2021-03-23T11:22:21.143Z - [32minfo[39m: Rendering request 11 finished in 868 ms
2021-03-23T11:22:21Z   [Information]   Executed 'Functions.HttpTrigger1' (Succeeded, Id=45f41e6c-ac97-4f78-baa9-cb692b8dc105, Duration=881ms)

I tried to restart function app, it didn't help. But when I redeploy the function, it starts work fine for a while. Maybe you could suggest me where to dig? Probably, there are some limitations for templates?

**Comment by pofider** [comment] 2021-03-23 12:21
Thank you. It's a bit suspicious that the rendering was so fast... 868ms for 15 pages...
Are you sure that with the same input json, the template produces empty pdf once and the other time normal result?
Could you try to run the template locally with the json that is causing the blank result?

It could be interesting to know what HTML is actually chrome converting. Try to run the template with HTML recipe after you get the blank result and observe the output.

**Comment by yauheni-p** [comment] 2021-03-23 12:41
Yes, I'm sure. I use postman to call azure function and I don't change request at all.

1 - failed result
![image](https://user-images.githubusercontent.com/45207703/112146594-d2cb1780-8bec-11eb-85c2-5cd74c05501d.png)

2 - result after redeploy
![image](https://user-images.githubusercontent.com/45207703/112146612-d8c0f880-8bec-11eb-8516-fb558b434606.png)

When I run the template locally it always works fine (at least I didn't receive empty results)

**Comment by pofider** [comment] 2021-03-24 09:23
Please try to run the template with HTML recipe after you get the blank result and observe the output.

**Comment by lloedolff** [comment] 2022-04-04 03:04
I am also getting similar inconsistence issues when deploying jsReportst to Azure
When deploying with 5 reports, everything works perfectly, but when I deploy with 17 reports (using a valid license), I am getting random errors, including a blank page as a response, an error saying that is can't find the report's CSS file and an error saying that the report can't be found.
The odd thing is that it is not consistent, so one minute I would get the CSS error and 5 minutes later it would say it can't find the reports.

**Comment by pofider** [comment] 2022-04-04 15:42
@lloedolff  You may likely hit the problem fixed in this PR https://github.com/jsreport/jsreport-azure-functions-starter-kit/pull/3 I will check it and merge it tomorrow, I forget I have it in the queue.

**Comment by pofider** [comment] 2022-04-05 09:53
The problem mentioned here was fixed with the last commit https://github.com/jsreport/jsreport-azure-functions-starter-kit/commit/93a6cecc243cff5b2ac8a103d465cb68536acce4

The problem was caused by a bug in the initialization code described here https://github.com/jsreport/jsreport-azure-functions-starter-kit/pull/3

**Closed by pofider** 2022-04-05 09:53 UTC
